listener 1883
protocol mqtt
allow_anonymous false
password_file /etc/mosquitto/passwd
acl_file /etc/mosquitto/acl

# เปิด WebSocket port 9001 ให้ React Dashboard เชื่อมต่อมารับข้อมูลแบบ Real-time ได้
listener 9001
protocol websockets
